# This is a basic workflow to help you get started with Actions

name: Feature Building Test
# Controls when the workflow will run
on:
  push:
    branches:
      - 'feat/**' 
      - 'feature/**' 
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - run: git fetch --no-tags --prune --depth=1 origin main      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --mode skip-build

      - name: Yarn Affected Lint
        run: yarn nx affected --target=lint --base=origin/main --parallel=true --maxParallel=2

      - name: Yarn Affected Build
        run: yarn nx affected --target=build --base=origin/main --parallel=true --maxParallel=2

      - name: Yarn Affected Pack Server
        run: yarn nx affected --target=pack --base=origin/main --parallel=true --maxParallel=2